name: LongReads
channels:
    - https://metachannel.conda-forge.org/rmg,bioconda/--max-build-no
dependencies:
    - scrappie
    - minimap2
    - miniasm
    - racon
    - kraken2
    - krona
    - flye
    - samtools
