name: LongReads
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - canu
  - filtlong 
  - seqkit
  - kraken2 
  - krona
  - minimap2
  - racon
  - miniasm
  - flye
  - samtools
  - r-base