name: MetaHood
channels:
    - https://metachannel.conda-forge.org/bioconda,anaconda,conda-forge,default,ursky/--max-build-no
dependencies:
    - snakemake >=5.5.4
    - python
    - biopython
    - bowtie2 
    - samtools
    - prodigal
    - megahit
    - spades
    - blast =2.5.0
    - concoct
    - mafft
    - trimal
    - fasttree
    - gfapy
    - future
    - pysam
    - pygam
    - statsmodels
    - pathos
    - ete3
    - bwa
    - bedtools
    - parallel
    - bcbio-gff
    - kraken
    - bam-readcount
    - cython
    - fastqc 
    - multiqc
    - trim-galore
    - metabat2