# ------ Resssources ------ 
Percent_memory: 0.5 # maximum quantity of memory the snakemake can take
threads : 8 # single task nb threads
# ------ Path to data folder ------ 
data: /home/ubuntu/Project/InfantGut_Metahood/Data/ # path to data folder,   
# ------ Samples ------
# each sample need to have its own folder, with only 2 fastq files. Also, "fq.gz" are not detected. 
samples :
  setup : 1 
  file : /home/ubuntu/repos/Ebame19-Quince/Samples.csv
  folder: /home/ubuntu/Project/InfantGut_Metahood/Data/
# ------ Assembly parameters ------
assembly: 
  assembler: megahit # only option so far, won't change in the near future
  groups: 
      Coassembly:
        ['sample(?([0-7])']
# ------ Binning parameters------ 
binning :
  concoct :
    contig_size : 1000 # min contig size considered
    execution : 1 # execution either 1 or 0 for yes or no
  metabat2 :
    contig_size : 1500 # min contig size considered
    execution : 1 # execution either 1 or 0 for yes or no
# ------ MAG anaysis------ 
maganalysis : 1 # execution either 1 or 0 for yes or no
# ------ DESMAN anaysis------ 
desman : 
  execution : 0 # execution either 1 or 0 for yes or no
  scripts : "/home/ubuntu/repos/DESMAN/scripts"
  nb_haplotypes: 10
  nb_repeat: 5
  min_cov: 1