# ------ Resssources ------ 
Percent_memory: 0.5
threads : 8 # single task nb threads
# ------ Path to data folder ------ 
data: /mnt/ReadsSub
# ------ Assembly parameters ------ 
assembly: 
  assembler: megahit
  groups: 
      InfantGut:
        ['sample*']
# ------ Annotation parameters ------ 
cog_database: ~/Databases/rpsblast_cog_db
# ------ Binning parameters------ 
binning :
  concoct :
    contig_size : 1000
    execution : 1
  metabat2 :
    contig_size : 1500
    execution : 1
# ------ MAG anaysis------ 
maganalysis : 1 # execution either 1 or 0 for yes or no
# ------ DESMAN anaysis------ 
desman : 
  execution : 1 # execution either 1 or 0 for yes or no
  scripts : "~/repos/DESMAN"
  nb_haplotypes: 10
  nb_repeat: 5
  min_cov: 1